services:
  db:
      image: mysql:8.0.31
      container_name: ejemplo-db
      environment:
        - MYSQL_DATABASE=ejemplo
        - MYSQL_USER=ejemplo 
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=secret
      ports:
        - '3306:3306'
      expose:
        - '3306'
            # MySQLAdmin

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - 8081:80
      environment:
        - PMA_HOST=db        
